module Monsters.Types exposing (..)

type AttackType
    = Melee
    | Ranged
    | Poison
    | Acid
    | Fire
    | Ice
    | Lightning
    | Drain
    | Steal
    | Spell

type MonsterType
    = Kobold
    | GiantRat
    | LargeSnake
    | GiantRedAnt
    | WildDog
    | Skeleton
    | GiantTrapdoorSpider
    | GiantBat
    | CarrionCreeper
    | GiantScorpion
    | GreenSlime
    | Viper
    | HugeOgre
    | WalkingCorpse
    | HugeLizard
    | Goblin
    | Hobgoblin
    | Shadow
    | SmirkingSneakThief
    | GrayWolf
    | WhiteWolf
    | BrownBear
    | CaveBear
    | GelatinousGlob
    | GruesomeTroll
    | Manticore
    | AnimatedBronzeStatue
    | AnimatedIronStatue
    | AnimatedMarbleStatue
    | AnimatedWoodenStatue
    | Bandit
    | EvilWarrior
    | Wizard
    | Necromancer
    | BarrowWight
    | DarkWraith
    | EerieGhost
    | Spectre
    | Vampire
    | IceDevil
    | RatMan
    | WolfMan
    | BearMan
    | BullMan
    | SpikedDevil
    | HornedDevil
    | AbyssFiend
    | WindElemental
    | DustElemental
    | FireElemental
    | WaterElemental
    | MagmaElemental
    | IceElemental
    | EarthElemental
    | HillGiant
    | TwoHeadedGiant
    | FrostGiant
    | StoneGiant
    | FireGiant
    | Surtur
    | FireGiantKing
    | FrostGiantKing
    | HillGiantKing
    | StoneGiantKing
    | RedDragon
    | BlueDragon
    | WhiteDragon
    | GreenDragon

monsterTypesToList : List MonsterType
monsterTypesToList =
    [ Kobold
    , GiantRat
    , LargeSnake
    , GiantRedAnt
    , WildDog
    , Skeleton
    , GiantTrapdoorSpider
    , GiantBat
    , CarrionCreeper
    , GiantScorpion
    , GreenSlime
    , Viper
    , HugeOgre
    , WalkingCorpse
    , HugeLizard
    , Goblin
    , Hobgoblin
    , Shadow
    , SmirkingSneakThief
    , GrayWolf
    , WhiteWolf
    , BrownBear
    , CaveBear
    , GelatinousGlob
    , GruesomeTroll
    , Manticore
    , AnimatedBronzeStatue
    , AnimatedIronStatue
    , AnimatedMarbleStatue
    , AnimatedWoodenStatue
    , Bandit
    , EvilWarrior
    , Wizard
    , Necromancer
    , BarrowWight
    , DarkWraith
    , EerieGhost
    , Spectre
    , Vampire
    , IceDevil
    , RatMan
    , WolfMan
    , BearMan
    , BullMan
    , SpikedDevil
    , HornedDevil
    , AbyssFiend
    , WindElemental
    , DustElemental
    , FireElemental
    , WaterElemental
    , MagmaElemental
    , IceElemental
    , EarthElemental
    , HillGiant
    , TwoHeadedGiant
    , FrostGiant
    , StoneGiant
    , FireGiant
    , Surtur
    , FireGiantKing
    , FrostGiantKing
    , HillGiantKing
    , StoneGiantKing
    , RedDragon
    , BlueDragon
    , WhiteDragon
    , GreenDragon
    ]